language: go

go:
  - 1.10.x
  - 1.11.x

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.2/glide-v0.13.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install:
  - glide install

script:
  - cd job && go test
